title: Bioinformatics-scripts
description: This repository consists of specific bioinformatics problems solved by writing small scripts; majority of them in Python. The problems have been taken from open platforms like ROSALIND (http://rosalind.info/problems). Some of the scripts are solutions to my day-to-day challenges while working.
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
